// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcukplaooupsqvhqdjta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjdWtwbGFvb3Vwc3F2aHFkanRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MTA2MzcsImV4cCI6MjA3MDI4NjYzN30.5ewA_O3xJh57DRbODnFO3_dRVuZFY9uHRF6Fa4zsf0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});